"""
backend/schemas/report.py

Pydantic schemas for patient-facing Pre-Consultation Reports and Documents.
Exposes a clean read-model view over existing persisted records:
Patient, Encounter, IntakeSession, ExtractedEntity, ClinicalSummary, TimelineEvent, Document.
"""

from __future__ import annotations
from typing import Optional, List, Dict, Any
from pydantic import BaseModel


class PatientEntityEvidence(BaseModel):
    """Structured AI evidence extracted during intake."""
    field_name: str
    label: str
    value: str
    original_ai_value: Optional[str] = None
    confidence: float
    low_confidence_flag: bool
    verification_status: str  # unreviewed | accepted | edited | rejected
    source_type: str          # intake_session | document
    source_location: Optional[str] = None
    source_document_id: Optional[str] = None
    source_document_name: Optional[str] = None
    reviewed_by: Optional[str] = None
    reviewed_at: Optional[str] = None

    model_config = {"from_attributes": True}


class PatientDocumentItem(BaseModel):
    """Document uploaded by patient."""
    id: str
    document_id: Optional[str] = None
    encounter_id: str
    patient_id: Optional[str] = None
    document_type: str
    original_filename: Optional[str] = None
    filename: Optional[str] = None
    upload_timestamp: str
    uploaded_at: Optional[str] = None
    processing_status: str = "processed"
    processing_error: Optional[str] = None
    file_size: Optional[int] = None
    mime_type: Optional[str] = None
    entity_count: int = 0
    extracted_entity_count: Optional[int] = None
    extracted_entities: List[PatientEntityEvidence] = []


class PatientTimelineItem(BaseModel):
    """Longitudinal event in patient intake timeline."""
    id: str
    event_type: str
    date: Optional[str] = None
    date_confidence: float
    date_uncertain: bool
    created_at: str

    model_config = {"from_attributes": True}


class PatientReportSummaryItem(BaseModel):
    """Summary item for listing patient reports on dashboard and reports index."""
    encounter_id: str
    patient_id: str
    opd_department: Optional[str] = None
    consultation_date: str
    queue_status: str              # ready_for_review | completed
    doctor_review_status: str       # Awaiting Doctor Review | Doctor Verified | Completed
    has_summary: bool
    total_entities: int
    unreviewed_count: int
    summary_preview: Optional[str] = None


class PatientMissingField(BaseModel):
    """A field defined by the clinical schema that was not captured during intake."""
    field_name: str
    label: str
    status: str = "Not provided"


class PatientReportDetailResponse(BaseModel):
    """
    Comprehensive structured Pre-Consultation Report document view.
    Assembled dynamically from canonical database records.
    """
    # 1. Patient Information
    patient_id: str
    patient_name: str
    patient_uid: str                # Authoritative Patient record ID
    encounter_id: str
    opd_department: Optional[str] = None
    consultation_date: str
    created_at: str

    # 2. Status & Doctor Review
    queue_status: str               # ready_for_review | completed
    doctor_review_status: str       # Awaiting Doctor Review | Doctor Verified | Completed
    doctor_notes: Optional[str] = None
    doctor_user_id: Optional[str] = None

    # 3. Clinical Summary (Generated by brain.py at intake submit)
    summary_text: Optional[str] = None
    summary_generated_at: Optional[str] = None

    # 4. Chief Complaint & History of Presenting Complaint
    chief_complaint: Optional[str] = None
    hpi_details: Dict[str, str] = {}

    # 5. Categorized Medical History
    medical_history: List[str] = []
    medications: List[str] = []
    allergies: List[str] = []
    investigations: List[str] = []
    investigation_details: Dict[str, str] = {}
    other_history: Dict[str, str] = {}

    # 6. Schema Fields Not Captured ("Not provided" - never inferred)
    missing_fields: List[PatientMissingField] = []

    # 7. AI Extraction Evidence with full provenance & confidence
    extracted_entities: List[PatientEntityEvidence] = []

    # 8. Documents Reviewed
    documents_count: int = 0
    documents: List[PatientDocumentItem] = []

    # 9. Longitudinal Timeline
    timeline: List[PatientTimelineItem] = []


class PatientDashboardMetrics(BaseModel):
    """Real metric counts derived exclusively from persisted patient records."""
    consultations_count: int
    documents_count: int
    reports_count: int
